eureka:
  client:
    service-url:
        #设置Eureka Server的交互地址，注册服务
        #defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
        defaultZone: http://localhost:8761/eureka/
  #instance:
    #自定义客户端的主机名称
  #  hostname: demoClent
spring:
  application:
    #为服务命名
    name: product
server:
  port: 8080
